---
- name: Restart Service after Updating Configuration
  hosts: "{{ host }}"
  become: yes
  become_method: sudo

  tasks:

    - name: Copy updated configuration file
      copy:
        src: "{{ src_path }}"
        dest: "/home/{{ user }}/cron.txt"

    - name: Update cron
      become: yes
      shell: "crontab  -u {{ user }} /home/{{ user }}/cron.txt"

    - name: Delete cron.txt after applying changes
      file:
        path: "/home/{{ user }}/cron.txt"
        state: absent